version: '3.9'
services:
  nginx:
    build: 
      context: './nginx'
      dockerfile: Dokerfile
    ports:
      -80:80
    restart: unless-stopped
#     image: nginx:stable-alpine
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#     ports:
#       - 80:80
#     restart: unless-stopped
#     depends_on:
#       - api
#     networks:
#       - nginx-networks
#   api:
#     build: 
#       dockerfile: Dockerfile
#     expose:
#       - 5050
#     restart : unless-stopped
#     networks:
#       - nginx-networks
# networks:
#   nginx-networks: 
#     driver: bridge 
