version: '3.8'
name: fullstackhero
volumes:
  postgres-data:
  # sebp-elk-data:
networks:
  fullstackhero:
    driver: bridge
services:
  dotnet-webapi:
    #image: iammukeshm/dotnet-webapi:latest
    container_name: dotnet-webapi
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - fullstackhero
    environment:
     # - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:5010;https://+:5011
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Urmatbek82
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - DatabaseSettings__ConnectionString=Server=postgres;Port=5432;Database=fshdb;User Id=postgres;Password=postgres; IntegratedSecurity=true; Pooling=true;
      - HangfireSettings__Storage__ConnectionString=Server=postgres;Port=5432;Database=fshdb;User Id=postgres;Password=postgres; IntegratedSecurity=true; Pooling=true;
      - DatabaseSettings__DBProvider=postgresql
      - HangfireSettings__Storage__StorageProvider=postgresql
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "8080:5010"
      - "8081:5011"
    depends_on:
      - postgres
    restart: on-failure
    #----------------------
  dotnet-wasm:
    #image: iammukeshm/dotnet-webapi:latest
    container_name: dotnet-wasm
    build:
      context: ../CountrymenFund-wasm/.
      dockerfile: Dockerfile
    networks:
      - fullstackhero
    environment:
     # - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80;http://+:443
      - ASPNETCORE_URLS=http://+:5010;https://+:5011
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Urmatbek82
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dotnet-webapi
    restart: on-failure
    #-----------
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - fullstackhero
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fshdb
      - PGPORT=5432
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgres-data:/data/db
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U admin"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  # elk:
  #     container_name:  elasticsearch-kibana
  #     image: sebp/elk:oss-8.5.3
  #     environment:
  #       - LOGSTASH_START=0
  #     volumes:
  #       - sebp-elk-data:/usr/share/elk/data
  #     ports:
  #       - 5601:5601
  #       - 9200:9200
  #     networks:
  #       - fullstackhero
