version: '3.8'
name: fullstackhero
volumes:
  postgres-data:
  pgadmin-data:
  # sebp-elk-data:
networks:
  fullstackhero:
    driver: bridge
services:
  webapi:
    #image: iammukeshm/dotnet-webapi:latest
    container_name: webapi
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - fullstackhero
    environment:
     # - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Urmatbek82
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - DatabaseSettings__ConnectionString=Server=postgres;Port=5432;Database=fshdb;User Id=postgres;Password=postgres; IntegratedSecurity=true; Pooling=true;
      - HangfireSettings__Storage__ConnectionString=Server=postgres;Port=5432;Database=fshdb;User Id=postgres;Password=postgres; IntegratedSecurity=true; Pooling=true;
      - DatabaseSettings__DBProvider=postgresql
      - HangfireSettings__Storage__StorageProvider=postgresql
    volumes:
      - ~/.aspnet/https:/https:ro
      - /files:/Files
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    restart: on-failure
    #----------------------
  wasm:
    #image: iammukeshm/dotnet-webapi:latest
    container_name: wasm
    build:
      context: ../CountrymenFund-wasm/.
      dockerfile: Dockerfile
    networks:
      - fullstackhero
    environment:
     # - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Urmatbek82
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapi
    restart: on-failure
    #-----------
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - fullstackhero
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fshdb
      - PGPORT=5432
      - PGDATA=/data/db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgres-data:/data/db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8082:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - fullstackhero
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U admin"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  # elk:
  #     container_name:  elasticsearch-kibana
  #     image: sebp/elk:oss-8.5.3
  #     environment:
  #       - LOGSTASH_START=0
  #     volumes:
  #       - sebp-elk-data:/usr/share/elk/data
  #     ports:
  #       - 5601:5601
  #       - 9200:9200
  #     networks:
  #       - fullstackhero
